---
title: "Study design"
format: html
editor: visual
bibliography: references.bib
---

Jeg har valgt å ta for meg et tema som omhandler intervalltrening og det maksimale oksygenopptaket (VO~2maks~). VO~2maks~ kan defineres som kroppens maksimale evne til å ta opp og omsette oksygen, altså den maksimale hastigheten på den aerobe energiomsetningen. Flick's likning illustrerer de bestemmede faktorene for VO~2maks~ som er minuttvolum (MV), arteriell O~2~ (aO~2~) og venøs O~2~ (vO~2~).

VO~2maks~ er assosiert med både helse og prestasjon, og det er derfor et interessant tema som i større eller mindre grad angår alle. Kunnskap knyttet til trening for å forbedre VO~2maks~ er relevant både når det kommer til mange former for toppidrett og prestasjon, men også for generell helse blandt befolknigen. Intervalltrening er i mange tilfeller en mer tidseffektiv treningsform som for mange kan være lettere å sette av tid til i en hektisk hverdag. Dersom intervalltrening har like gode eller bedre effekt på helsen enn en mer langvarig form for trening, vil det være positivt for folkehelsen da flere har tid til det. Samtidig har vi også en mindre del av beofolkningen som er opptatt av prestasjon, og i deres tilfelle er det nyttig å vite hvilken treningsform som belaster kroppen minst og krever minst restitusjon samtidig som man får størst treningseffekt. I en toppidrettshverdag handler det om å optimalisere alle faktorer i hverdagen for best mulig prestasjon og restitusjon. Da er denne formen for kunnskap nyttig da den kan bidra til å strukturere hverdagen og treningen på best mulig måte slik at hver enkelt på best mulig måte kan legge opp treningen etter sine egne behov.

Felles for alle studiene jeg har valgt ut er at de ønsker å undersøke hvilken effekt intervallpreget trening har på VO~2maks~ sammenliknet med kontinuerlig arbeid. Studiene har litt ulike tilnærminger til temaet med noe varierende hypoteser eller problemstillinger. @daussin2007 undersøkte hypotesen om at kontinuerlig trening og intervalltrening påvirker hhv. perifere og/eller sentrale faktorer. @astorino2013 og @helgerud2007 ønsket å sammenlikne endringer i det maksimale oksygenopptaket som respons på ulike treningsregimer. @nybo2010 hadde fokus på effektivitet i treningen og hadde som hensikt å undersøke effekten av høyintensiv intervalltrening sammenliknet med kontinuerlig arbeid og styrketrening på en rekke helseparametere, deriblandt det maksimale oksygenopptaket. @matsuo2014 hadde på lik linje med Nybo fokus på effektivitet og hadde som hensikt å der han sammenliknet tidseffektiv høyintensiv intervalltrening og kontinuerlig arbeid. I tillegg til dette er samtlige studier, med unntak av Helgerud et al. gjort på utrente. Studiene initierer at de tror intervalltrening utført med høy intensitet vil gi bedre adaptasjoner enn kontinuerlig trening, men de ønsker å undersøke hvor stor den eventuelle forskjellen er samt diskutere årsaksforklaringer.

Flere at studiene har mange likhetstrekk i valg av metode, men det er noen ulikheter. Alle studiene er intervensjonsstudier over en periode på 8-12 (28) uker med pre- og post-tester. @daussin2007 har også en detreningsperiode på etterfulgt av en ny intervensjon der gruppene bytter treningsform, og er den eneste av disse fem studiene som har en randomisert crossover design. @astorino2013 og @nybo2010 har begge en randomisert kontrollert between group design. @helgerud2007 og @matsuo2014 hadde en randomisert between group design, altså uten en kontrollgruppe. Det er verdt å nevne at i stuien til @matsuo2014 er gruppene kun delvis randomisert da gruppene er basert på deltakernes alder og VO2maks pre-intervensjon. Hensikten med dette er å øke studiens pålitelighet ved å gjøre gruppene så like som mulig for å sikre at eventuelle effekter av en intervensjon ikke kan tilskrives forskjeller mellom gruppene.

I en crossover studie trenger man ikke like mange deltakere som i de andre studiedesignene fordi hver deltaker gjennomfører begge intervensjonene samtidig som de fungerer som sin egen kontroll. Ulemper ved denne studiedesignen er at den varer over dobbelt så lenge som mange andre intervensjonsstudier, som kan påvirke rekruttering av deltakere og deltakernes motivasjon underveis. Det er også tenkelig at deltakerne kan ha en "carryover" effekt av de førsste intervensjonen som de tar med seg inn i den andre til tross for en detreningsperiode @designin2013. I studien til @daussin2007 er denne perioden satt til 12 uker og man tenker at deltakerne vil komme tilbake til baseline i løpet av denne perioden slik at de begynner med den andre intevrensjonen med "blanke ark". I de andre studiene trengs det et større utvalg fra populasjonen som videre deles inn i to eller flere grupper der hver gruppe gjennomfører ulik trening. Noen studier har også grupper som er kontrollgrupper som ikke gjennomfører noen for for trening, men som gjennomfører testene. På grunn av måten disse studiene utføres trengs det flere deltakere, hvilket kan være utfordrende å få tak i. Fordelene med en kontrollgruppe er at man kan kontrollere for at det ikke er andre faktorer som kan ha påvirket resultatet. To av de radomiserte between group design studiene har en kontrollgruppe og to har ikke det.

Det er noe varierende utvalg i studiene. @daussin2007 har et utvalg på 10 (5 kvinner og 5 menn) i sin crossover studie med en gjennomsnittsalder på 47 år, mens de resterende fire har et utvalg som varierer fra 20-42 med gjennomsnittsaldere sm varierer fra 23-31 år. Det er kun studien til @matsuo2014 som nevner hvordan deltakerne ble rekruttert, resten av studiene nevner ikke dette. I denne studien ble deltakerne rekrutert via lokal markedsføring på universitetet og i lokalavisa. Alle studiene foruten studien til @helgerud2007 som har moderat trente personer, har friske men utrente deltakere. Det er også noe vaiasjon i kjønnsfordelingen. @daussin2007 hadde både kvinnelige og mannlige deltakere (5 + 5), @nybo2010, @matsuo2014 og @helgerud2007 hadde kunn menn, mens @astorino2013 kun hadde kvinnelige deltakere. Det er en kjent sak at det gjøres mer forskning på menn enn på kvinner, og det er derfor fint at noen studier også kan representere kvinner. Hvorvidt utvalget representerer den generelle befolkningen kan diskuteres, men utvalget representerer i det minste den gruppen av befolkningen med de deltakerkarakteristikkene utvalget har.

Hver av studiene har valgt seg ut en rekke tester de utførte både pre og post-intervensjonen. Felles for alle er at de gjennomflører VO~2maks~-tester både pre og post intervensjon. I tillegg til dette har flere av studiene en rekke andre tester som f.eks. laktatterskel, maks watt, maksimal arteriovenøs differanse og kardiovaskulære tester som blodtrykk og hjertefrekvens i hvile. @astorino2013 er den eneste av disse studiene som gjennomførte tester underveis i intervensjonen. Dette ble gjort hver tredje uke for å regne ut hvilken intensitet deltakerne skulle trene på.

Til slutt samler studiene resultatene etter intervensjonen er gjennomført. @astorino2013 brukte en two way analysis of variance with repeated emasures for å undersøke forskjeller i variablene som respons på trening. De resterende studiene har brukt en two way ANOVA with repeated measures for å undersøke forskjellene mellom gruppene og resultatene deres. @matsuo2014 har også gjort en power test for å undesøke hvor stor sample size de må ha for å øke den statistiske styrken i studien sin ved at sannsynligheten for at de resultatene de får er overførbare til dresten av befolkningen. De brukte en priori power test og kom frem til at de måtte ha minst 11 i hver gruppe. De rekrutterte derfor litt flere enn dette da de tok høyde for at noen muligens ville droppe ut underveis. @astorino2013 brukte en one way ANOVA til å undersøke forskjeller i deltakerkarakteristikker ved baseline mellom gruppene for å ha tatt høyde for dette når resultatene skal analyseres.

Alle studiene har kommet fram til at trening med høyere intensitet er bedre for å øke VO~2maks~ enn trening med lavere intensitet. Gruppene som ha trent med lavere intensitet har i de fleste tilfellene også økt sitt maksimale oksygenopptak, men gruppene med høyere intensitet har økt signifikant mer. Det betyr ikke nødvendigvis at den høyeste intensiteten er best. I studien til @matsuo2014 fikk gruppen som trente \<90% VO~2maks~ (HIAT) en større forbedring enn gruppen som trente på 120% VO~2maks~ (SIT). Arbeidstiden til HIAT gruppen var 13 min mens den kun var 5 min, hvilket kan ha spilt en rolle i resultatet. Det er nok lettere å opprettholde intensiteten HIAT-gruppen hadde over lengre tid, som er essensielt for å oppnå de adaptasjonene som er assosiert med et økt maksimalt oksygenopptak. De resterende studiene er enige i at intervalltrening med høy intensitet er å foretrekke fremfor både kontinuerlig trening og intervaller med lavere intensitet for å forbedre VO~2maks~ både hos friske utrente menn og kvinner, og hos moderat trente menn som har de samme fysike trekkene som gruppene som har utført nettopp disse studiene.
